### ISSUE TITLE
Resonite support 

### ISSUE THREAD

**Issue by troyBORG** [kazu0617/SessionTweaks#6]
Can this be updated for Resonite?

Also I know someone made a post on the YDMS GitHub about something referring to your mod:
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/97#issuecomment-1765731499

**Comment by kazu0617** [comment]
@troyBORG Okay! I'll release few days later.

**Comment by kazu0617** [comment]
I completed refactor about SessionTweaks. after Test, I'll release new version for resonite.

**Comment by kazu0617** [comment]
@troyBORG I released [v3.0.0](https://github.com/kazu0617/SessionTweaks/releases/tag/3.0.0) that supports Resonite.🎉
if it works, feel free to close this issue.

**Comment by troyBORG** [comment]
Ok.  I about to go to bed so can't check untill morning
